### ISSUE TITLE
Conversion functions

### ISSUE THREAD

**Issue by vallettea** [anthill/Python_OpeningHours#2]
This module should enable anyone to convert to and from python datetime objects to openingHour strings.

**Comment by Asphahyre** [comment]
I didn't understand...

Do you mean converting from the OpeningHours Python object into the OpeningHours' standard string we can use to build the object?

The only function that's using a datetime object is the `is_open` method:

```
    def is_open(self, date):
        return self.is_open_expended(date.minute, date.hour, date.day, date.month - 1, date.year - 1900, date.weekday())
```
