### ISSUE TITLE
Consider including C_OpeningHours as git submodule

### ISSUE THREAD

**Issue by ypid** [anthill/Python_OpeningHours#4]
This makes it much easier to handle external repos.

**Comment by Asphahyre** [comment]
I was handling this as a submodule, however there were some problems cloning or downloading the whole repository and the C_OpeningHours wasn't retrieved.
Currently, it's a subtree; would it be really better as a submodule?

**Comment by ypid** [comment]
> Currently, it's a subtree; would it be really better as a submodule?

I think submodules are a better fit for your use case. I personally have never found a good use case for git subtree and just checked it out in more details (refs: [Differences between git submodule and subtree](https://stackoverflow.com/questions/31769820/differences-between-git-submodule-and-subtree))

I also include an external library into the [opening_hours.js repo](https://github.com/opening-hours/opening_hours.js) and [git clone --recursive](https://github.com/opening-hours/opening_hours.js#for-developer) is everything to get the main repo and all submodules checked out. I like submodules and think they are a cleaner approach. You can just cd into your submodule and work as if it where an independent git repo (which can also have [it’s use cases](https://github.com/ypid/ypid-ansible-common/)) and it makes it more obvious where the actual source is (git subtree and successors seem to hide that).

If you find your submodules not cloned, a `git submodule update --init` does the job :wink:
