### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by thom4parisot** [anthill/Python_OpeningHours#5]
This is the content of my `requirements.txt` file:

```
opening_hours
```

pip install throws me this error:

```
Collecting ctypes (from opening_hours->-r requirements.txt (line 3))
  Could not find a version that satisfies the requirement ctypes (from opening_hours->-r requirements.txt (line 3)) (from versions: )
No matching distribution found for ctypes (from opening_hours->-r requirements.txt (line 3))
```

Do you know why?

**Comment by Asphahyre** [comment]
It seems you're missing ctypes, wich is needed to wrap the C++ library.
It also seems it wasn't available to install with `pip`…

I don't remember have it installed from here, but you will be able to do so [from sourceforge](https://sourceforge.net/projects/ctypes/files/).

**Comment by oncletom** [comment]
OK it seems `ctypes` has been renamed into `ctypeslib` and `ctypeslib2`. 

Will send a PR.

**Comment by thom4parisot** [comment]
Hm well, would it be possible to republish the package on pip?

The reason why the install fails is because it has an explicit dependency on `ctypes` and pip is unable to resolve it:

```
    install_requires=[
        'ctypes'
    ],
```

Thanks

**Comment by thom4parisot** [comment]
#7 should be merged and version bumped before releasing actually :-)

**Comment by Asphahyre** [comment]
Is it that? https://github.com/trolldbois/ctypeslib

In their examples they do import `ctypes`, which does not appear in their repository nor in their dependancies…
https://github.com/trolldbois/ctypeslib/blob/master/docs/ctypeslib%202.0%20Introduction.ipynb

Should I simply remove the `install_requires` section?

**Comment by thom4parisot** [comment]
@Asphahyre sorry about mentioning `ctypeslib`, I made a mistake a deleted my previous comment as a consequence.

Although yes, `ctypes` should be removed from `install_requires` as I found out it is [a standard library](https://docs.python.org/2/library/ctypes.html). It is absent from `setup.py` in the current master branch *but* not in the the artifact of `opening_hours` hosted on pip:

```py
#!/usr/bin/python

from setuptools import setup
from subprocess import call
import sys
import os
import codecs

if (len(sys.argv) > 1 and (sys.argv[1] == "build" or sys.argv[1] == "install")):
    if (call(["make", "-C", "C_OpeningHours"])):
        sys.exit(1)
    if (sys.argv[1] == "install"):
	if (call(["make", "-C", "C_OpeningHours", "install"])):
            sys.exit(1)
    else:
        sys.exit(0)

long_description = ''
if os.path.exists('README.md'):
    long_description = codecs.open('README.md', encoding='UTF-8', mode='r').read()

setup(
    name         = 'opening_hours',
    version      = '0.1.0',
    description  = 'Python wrapper embedding the C_OpeningHours writing on my own, implementation of the opening hours standard as described here: https://wiki.openstreetmap.org/wiki/Key:opening_hours',
    author       = 'Luka Boulagnon (Asphahyre) during internship at WeAreAnts.fr',
    author_email = 'asphahyre@geluti.org',
    url          = 'https://github.com/anthill/Python_OpeningHours',
    packages     = ['opening_hours'],
    license      = 'MIT',
    keywords     = ['OSM', 'OpenStreetMap', 'opening_hours'],
    install_requires=[
        'ctypes'
    ],
    long_description = long_description,
)
```

**Comment by Asphahyre** [comment]
Indeed, I will correct it.
Thank you! :-)

**Comment by Asphahyre** [comment]
Updated!

https://pypi.python.org/pypi/opening_hours/

**Comment by thom4parisot** [comment]
Thanks @Asphahyre :-)
